// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using demo.Data;

#nullable disable

namespace demo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("demo.Models.Shirt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<double?>("Price")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<int?>("Size")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Shirts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Nike",
                            Color = "red",
                            Gender = "men",
                            Price = 49.990000000000002,
                            Size = 8
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Adidas",
                            Color = "blue",
                            Gender = "women",
                            Price = 39.990000000000002,
                            Size = 7
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Puma",
                            Color = "green",
                            Gender = "men",
                            Price = 29.989999999999998,
                            Size = 12
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Reebok",
                            Color = "black",
                            Gender = "women",
                            Price = 59.990000000000002,
                            Size = 6
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Under Armour",
                            Color = "gray",
                            Gender = "men",
                            Price = 79.989999999999995,
                            Size = 9
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Fila",
                            Color = "white",
                            Gender = "women",
                            Price = 34.990000000000002,
                            Size = 7
                        },
                        new
                        {
                            Id = 7,
                            Brand = "New Balance",
                            Color = "purple",
                            Gender = "men",
                            Price = 54.990000000000002,
                            Size = 10
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Asics",
                            Color = "yellow",
                            Gender = "women",
                            Price = 44.990000000000002,
                            Size = 11
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
